window.speciesData = {
    "sonabat_western_na_bats": {
        "source_name": "SonoBat: Echolocation Call Characteristics of Western North American Bats",
        "source_href": "https://sonobat.com/download/Western_NA_Bat_Acoustic_Table.pdf",
        "species": [
            {
                "species": "Macrotus californicus",
                "code": "Maca",
                "common_name": "California Leaf-nosed bat",
                "fc_mean": 56.9,
                "fc_stddev": [60, 53],
                "fc_range": [47, 67],
                "fhi_mean": 80,
                "fhi_stddev": [85, 75],
                "fhi_range": [62, 98],
                "flo_mean": 50.6,
                "flo_stddev": [55, 47],
                "flo_range": [40, 62],
                "fmaxE_mean": 62.4,
                "fmaxE_stddev": [66,58],
                "fmaxE_range": [48,75],
                "dur_mean": 3.6,
                "dur_stddev": [4.6, 2.6],
                "dur_range": [1.6, 7.0],
                "uppr_slope": 13.3,
                "uppr_slope_stddev": [17, 10],
                "uppr_slope_range": [3.8, 31],
                "lwr_slope": 5.6,
                "lwr_slope_stddev": [7.0, 4.2],
                "lwr_slope_range": [2.0, 12],
                "slope_fc": 5.5,
                "slope_fc_stddev": [8.3, 2.7],
                "slope_fc_range": [0, 20],
                "domnt_slope": 6.1,
                "domnt_slope_stddev": [8.5, 3.7],
                "domnt_slope_range": [2.1, 21]
            },
            {
                "species": "Myotis yumanensis",
                "code": "Myyu",
                "common_name": "Yuma myotis",
                "fc_mean": 51.2,
                "fc_stddev": [54,49],
                "fc_range": [45,59],
                "fhi_mean": 85.9,
                "fhi_stddev": [99,73],
                "fhi_range": [53,129],
                "flo_mean": 45.3,
                "flo_stddev": [48,43],
                "flo_range": [37,53],
                "fmaxE_mean": 54.1,
                "fmaxE_stddev": [60,49],
                "fmaxE_range": [45,95],
                "dur_mean": 5.2,
                "dur_stddev": [6.4,4.0],
                "dur_range": [1.8,8.6],
                "uppr_slope": 16.2,
                "uppr_slope_stddev": [22,11],
                "uppr_slope_range": [1.4,41],
                "lwr_slope": 4.2,
                "lwr_slope_stddev": [6.5,2.0],
                "lwr_slope_range": [0.9,17],
                "slope_fc": 2.9,
                "slope_fc_stddev": [4.8,1.1],
                "slope_fc_range": [0,17],
                "domnt_slope": 4.3,
                "domnt_slope_stddev": [8.4,0.7],
                "domnt_slope_range": [0.7,35]
            },
            {
                "species": "Myotis californicus",
                "code": "Myca",
                "common_name": "California myotis",
                "fc_mean": 49.5,
                "fc_stddev": [52,47],
                "fc_range": [43,57],
                "fhi_mean": 91.0,
                "fhi_stddev": [106,76],
                "fhi_range": [52,135],
                "flo_mean": 43.4,
                "flo_stddev": [47,40],
                "flo_range": [33,53],
                "fmaxE_mean": 53.0,
                "fmaxE_stddev": [59,47],
                "fmaxE_range": [33,101],
                "dur_mean": 3.8,
                "dur_stddev": [4.8,2.8],
                "dur_range": [1.6,7.3],
                "uppr_slope": 22.9,
                "uppr_slope_stddev": [33,15],
                "uppr_slope_range": [2.4,56],
                "lwr_slope": 6.8,
                "lwr_slope_stddev": [10,3.9],
                "lwr_slope_range": [0.1,25],
                "slope_fc": 3.5,
                "slope_fc_stddev": [7,0.4],
                "slope_fc_range": [0,27],
                "domnt_slope": 9.7,
                "domnt_slope_stddev": [19,1.0],
                "domnt_slope_range": [1.0,57]
            },
            {
                "species": "Parastrellus hesperus",
                "code": "Pahe",
                "common_name": "Canyon bat",
                "fc_mean": 46.1,
                "fc_stddev": [48,44],
                "fc_range": [41,53],
                "fhi_mean": 62,
                "fhi_stddev": [73,51],
                "fhi_range": [44,101],
                "flo_mean": 45,
                "flo_stddev": [47,44],
                "flo_range": [40,51],
                "fmaxE_mean": 48,
                "fmaxE_stddev": [50,46],
                "fmaxE_range": [42,57],
                "dur_mean": 5.2,
                "dur_stddev": [6.2,4.2],
                "dur_range": [2.8,11],
                "uppr_slope": 9.4,
                "uppr_slope_stddev": [18,1.3],
                "uppr_slope_range": [0.7,47],
                "lwr_slope": 1.1,
                "lwr_slope_stddev": [2.0,0.2],
                "lwr_slope_range": [0,6.8],
                "slope_fc": 0.8,
                "slope_fc_stddev": [1.8,0],
                "slope_fc_range": [0,8.5],
                "domnt_slope": 1.1,
                "domnt_slope_stddev": [2.0,0.2],
                "domnt_slope_range": [0,12]
            },
            {
                "species": "Choeronycteris mexicana",
                "code": "Chme",
                "common_name": "Mexican longtongued bat",
                "fc_mean": 44.2,
                "fc_stddev": [48,40],
                "fc_range": [36,52],
                "fhi_mean": 63.7,
                "fhi_stddev": [78,51],
                "fhi_range": [40,90],
                "flo_mean": 40.6,
                "flo_stddev": [45,36],
                "flo_range": [34,49],
                "fmaxE_mean": 49.0,
                "fmaxE_stddev": [58,40],
                "fmaxE_range": [33,70],
                "dur_mean": 2.7,
                "dur_stddev": [3.4,2.1],
                "dur_range": [1.7,4.8],
                "uppr_slope": 14.3,
                "uppr_slope_stddev": [24,5],
                "uppr_slope_range": [2.1,44],
                "lwr_slope": 4.9,
                "lwr_slope_stddev": [6.9,2.8],
                "lwr_slope_range": [0.7,11],
                "slope_fc": 3.9,
                "slope_fc_stddev": [6.6,1.3],
                "slope_fc_range": [0.3,13],
                "domnt_slope": 6.5,
                "domnt_slope_stddev": [9.5,3.6],
                "domnt_slope_range": [1.9,16]
            },
            {
                "species": "Lasiurus frantzii (blossevillii)",
                "code": "Labl",
                "common_name": "Western red bat",
                "fc_mean": 43.4,
                "fc_stddev": [48,39],
                "fc_range": [34,56],
                "fhi_mean": 64.7,
                "fhi_stddev": [79,51],
                "fhi_range": [39,107],
                "flo_mean": 42.4,
                "flo_stddev": [46,38],
                "flo_range": [33,54],
                "fmaxE_mean": 46.1,
                "fmaxE_stddev": [52,40],
                "fmaxE_range": [36,91],
                "dur_mean": 7.2,
                "dur_stddev": [9.4,5.1],
                "dur_range": [2.2,16],
                "uppr_slope": 7.3,
                "uppr_slope_stddev": [13,1.6],
                "uppr_slope_range": [0.4,40],
                "lwr_slope": 1.7,
                "lwr_slope_stddev": [3.7,0],
                "lwr_slope_range": [0,17],
                "slope_fc": 1.0,
                "slope_fc_stddev": [2.4,0],
                "slope_fc_range": [0,16],
                "domnt_slope": 2.2,
                "domnt_slope_stddev": [5.5,0],
                "domnt_slope_range": [0,43]
            },
            {
                "species": "Leptonycteris species",
                "code": "Lesp",
                "common_name": "Mexican longnosed bat",
                "fc_mean": 38.6,
                "fc_stddev": [43,34],
                "fc_range": [27,56],
                "fhi_mean": 72,
                "fhi_stddev": [86,58],
                "fhi_range": [42,113],
                "flo_mean": 32.4,
                "flo_stddev": [43.6,29],
                "flo_range": [23,45],
                "fmaxE_mean": 43.6,
                "fmaxE_stddev": [49,38],
                "fmaxE_range": [30,61],
                "dur_mean": 7.5,
                "dur_stddev": [9.5,5.4],
                "dur_range": [1.9,14],
                "uppr_slope": 10.6,
                "uppr_slope_stddev": [16,5.2],
                "uppr_slope_range": [1.9,42],
                "lwr_slope": 3.3,
                "lwr_slope_stddev": [5.0,1.7],
                "lwr_slope_range": [0.5,13],
                "slope_fc": 2.9,
                "slope_fc_stddev": [4.5,1.2],
                "slope_fc_range": [0,12],
                "domnt_slope": 3.2,
                "domnt_slope_stddev": [4.8,1.5],
                "domnt_slope_range": [0.3,13]
            },
            {
                "species": "Myotis ciliolabrum",
                "code": "Myci",
                "common_name": "Small-footed myotis",
                "fc_mean": 42.7,
                "fc_stddev": [45,41],
                "fc_range": [38,48],
                "fhi_mean": 83.3,
                "fhi_stddev": [98.1,68],
                "fhi_range": [51,119],
                "flo_mean": 37.0,
                "flo_stddev": [40,34],
                "flo_range": [28,43],
                "fmaxE_mean": 46.3,
                "fmaxE_stddev": [52,41],
                "fmaxE_range": [39,87],
                "dur_mean": 3.8,
                "dur_stddev": [4.5,3.1],
                "dur_range": [1.7,5.7],
                "uppr_slope": 23.9,
                "uppr_slope_stddev": [33,15],
                "uppr_slope_range": [4.9,53],
                "lwr_slope": 6.3,
                "lwr_slope_stddev": [8.7,4.0],
                "lwr_slope_range": [0.4,16],
                "slope_fc": 2.7,
                "slope_fc_stddev": [4.6,0.9],
                "slope_fc_range": [0,12],
                "domnt_slope": 7.2,
                "domnt_slope_stddev": [12,2.7],
                "domnt_slope_range": [1.2,29]
            },
            {
                "species": "Myotis volans",
                "code": "Myvo",
                "common_name": "Hairy-winged myotis",
                "fc_mean": 42.7,
                "fc_stddev": [45,40],
                "fc_range": [37,52],
                "fhi_mean": 81.1,
                "fhi_stddev": [95,67],
                "fhi_range": [49,121],
                "flo_mean": 36.3,
                "flo_stddev": [39,34],
                "flo_range": [27,44],
                "fmaxE_mean": 45.8,
                "fmaxE_stddev": [50,41],
                "fmaxE_range": [39,97],
                "dur_mean": 4.0,
                "dur_stddev": [5,3],
                "dur_range": [1.6,7.6],
                "uppr_slope": 16.7,
                "uppr_slope_stddev": [23,11],
                "uppr_slope_range": [3.3,50],
                "lwr_slope": 7.2,
                "lwr_slope_stddev": [10,4.4],
                "lwr_slope_range": [0.1,24],
                "slope_fc": 4.8,
                "slope_fc_stddev": [7.8,1.7],
                "slope_fc_range": [0,26],
                "domnt_slope": 9.5,
                "domnt_slope_stddev": [15,3.7],
                "domnt_slope_range": [1.7,36]
            },
            {
                "species": "Myotis velifer",
                "code": "Myve",
                "common_name": "Cave myotis",
                "fc_mean": 42.1,
                "fc_stddev": [44,40],
                "fc_range": [37,49],
                "fhi_mean": 75.7,
                "fhi_stddev": [88,64],
                "fhi_range": [48,111],
                "flo_mean": 38.7,
                "flo_stddev": [41,36],
                "flo_range": [30,45],
                "fmaxE_mean": 44.8,
                "fmaxE_stddev": [49,41],
                "fmaxE_range": [37,68],
                "dur_mean": 5.1,
                "dur_stddev": [6.3,3.9],
                "dur_range": [1.7,7.5],
                "uppr_slope": 13.7,
                "uppr_slope_stddev": [18,9.1],
                "uppr_slope_range": [2.3,32],
                "lwr_slope": 4.1,
                "lwr_slope_stddev": [6.0,2.2],
                "lwr_slope_range": [0.7,15],
                "slope_fc": 1.8,
                "slope_fc_stddev": [3.4,0.3],
                "slope_fc_range": [0,11],
                "domnt_slope": 5.1,
                "domnt_slope_stddev": [9.6,0.6],
                "domnt_slope_range": [0.6,33]
            },
            {
                "species": "Myotis lucifugus",
                "code": "Mylu",
                "common_name": "Little brown bat",
                "fc_mean": 42,
                "fc_stddev": [44,40],
                "fc_range": [37,48],
                "fhi_mean": 69.1,
                "fhi_stddev": [81,58],
                "fhi_range": [45,111],
                "flo_mean": 38.5,
                "flo_stddev": [41,36],
                "flo_range": [30,45],
                "fmaxE_mean": 44,
                "fmaxE_stddev": [47,41],
                "fmaxE_range": [38,61],
                "dur_mean": 5.9,
                "dur_stddev": [7.2,4.6],
                "dur_range": [1.6,10],
                "uppr_slope": 10.8,
                "uppr_slope_stddev": [16,5.1],
                "uppr_slope_range": [1.5,16],
                "lwr_slope": 3.2,
                "lwr_slope_stddev": [5.1,1.2],
                "lwr_slope_range": [0.4,16],
                "slope_fc": 1.6,
                "slope_fc_stddev": [3.2,0.1],
                "slope_fc_range": [0,14],
                "domnt_slope": 3.3,
                "domnt_slope_stddev": [6.0,0.7],
                "domnt_slope_range": [0.2,29]
            },
            {
                "species": "Myotis Auriculus",
                "code": "Myar",
                "common_name": "Southwestern myotis",
                "fc_mean": 40.6,
                "fc_stddev": [45,36],
                "fc_range": [31,54],
                "fhi_mean": 81.4,
                "fhi_stddev": [97,66],
                "fhi_range": [45,123],
                "flo_mean": 32.7,
                "flo_stddev": [37,28],
                "flo_range": [18,44],
                "fmaxE_mean": 44.5,
                "fmaxE_stddev": [50,39],
                "fmaxE_range": [36,74],
                "dur_mean": 4.0,
                "dur_stddev": [5.1,3.0],
                "dur_range": [1.6,7.6],
                "uppr_slope": 19.2,
                "uppr_slope_stddev": [26,12],
                "uppr_slope_range": [4.2,44],
                "lwr_slope": 8.1,
                "lwr_slope_stddev": [12,4.2],
                "lwr_slope_range": [2.3,26],
                "slope_fc": 5.6,
                "slope_fc_stddev": [9.8,1.8],
                "slope_fc_range": [0,31],
                "domnt_slope": 10.0,
                "domnt_slope_stddev": [18,2.4],
                "domnt_slope_range": [2.2,44]
            },
            {
                "species": "Myotis evotis",
                "code": "Myev",
                "common_name": "Long-eared myotis",
                "fc_mean": 36,
                "fc_stddev": [38,34],
                "fc_range": [30,43],
                "fhi_mean": 76,
                "fhi_stddev": [91,61],
                "fhi_range": [46,129],
                "flo_mean": 27.5,
                "flo_stddev": [30,25],
                "flo_range": [21,38],
                "fmaxE_mean": 39.6,
                "fmaxE_stddev": [44,35],
                "fmaxE_range": [31,64],
                "dur_mean": 3.8,
                "dur_stddev": [4.8,2.8],
                "dur_range": [1.6,7.6],
                "uppr_slope": 19.6,
                "uppr_slope_stddev": [29,13],
                "uppr_slope_range": [4.7,46],
                "lwr_slope": 8.6,
                "lwr_slope_stddev": [13,4.6],
                "lwr_slope_range": [1.8,28],
                "slope_fc": 5.7,
                "slope_fc_stddev": [10,1.7],
                "slope_fc_range": [0,31],
                "domnt_slope": 10.7,
                "domnt_slope_stddev": [18,3.6],
                "domnt_slope_range": [1.3,45]
            },
            {
                "species": "Lasiurus xanthinus",
                "code": "Laxa",
                "common_name": "Western yellow bat",
                "fc_mean": 33.6,
                "fc_stddev": [36,11],
                "fc_range": [26,40],
                "fhi_mean": 52.9,
                "fhi_stddev": [64,41],
                "fhi_range": [29,87],
                "flo_mean": 32.9,
                "flo_stddev": [35,31],
                "flo_range": [22,39],
                "fmaxE_mean": 36.3,
                "fmaxE_stddev": [41,32],
                "fmaxE_range": [27,58],
                "dur_mean": 6.9,
                "dur_stddev": [9.3,4.4],
                "dur_range": [2.5,15],
                "uppr_slope": 7.8,
                "uppr_slope_stddev": [13,2],
                "uppr_slope_range": [0.3,30],
                "lwr_slope": 1.5,
                "lwr_slope_stddev": [2.7,0.2],
                "lwr_slope_range": [0,7],
                "slope_fc": 0.8,
                "slope_fc_stddev": [1.5,0],
                "slope_fc_range": [0,6],
                "domnt_slope": 1.7,
                "domnt_slope_stddev": [3.2,0.2],
                "domnt_slope_range": [0,11]
            },
            {
                "species": "Antrozous pallidus",
                "code": "Anpa",
                "common_name": "Pallid bat",
                "fc_mean": 27.1,
                "fc_stddev": [30,25],
                "fc_range": [19,35],
                "fhi_mean": 52,
                "fhi_stddev": [60, 44],
                "fhi_range": [39,86],
                "flo_mean": 24.5,
                "flo_stddev": [27,22],
                "flo_range": [19,32],
                "fmaxE_mean": 30,
                "fmaxE_stddev": [33,27],
                "fmaxE_range": [21,57],
                "dur_mean": 11.5,
                "dur_stddev": [16,7.3],
                "dur_range": [4.7,26],
                "uppr_slope": 6.6,
                "uppr_slope_stddev": [10,3.1],
                "uppr_slope_range": [1.3,29],
                "lwr_slope": 2.1,
                "lwr_slope_stddev": [3.2,0.9],
                "lwr_slope_range": [0,8.1],
                "slope_fc": 1.2,
                "slope_fc_stddev": [2.1,0.3],
                "slope_fc_range": [0,6.3],
                "domnt_slope": 2.6,
                "domnt_slope_stddev": [4,1.3],
                "domnt_slope_range": [0,10]
            },
            {
                "species": "Eptesicus fuscus",
                "code": "Epfu",
                "common_name": "Big brown bat",
                "fc_mean": 28.2,
                "fc_stddev": [30,26],
                "fc_range": [21,35],
                "fhi_mean": 53.4,
                "fhi_stddev": [67,47],
                "fhi_range": [28,86],
                "flo_mean": 26.7,
                "flo_stddev": [28,25],
                "flo_range": [18,33],
                "fmaxE_mean": 31.4,
                "fmaxE_stddev": [36,28],
                "fmaxE_range": [22,59],
                "dur_mean": 7.9,
                "dur_stddev": [10,5.5],
                "dur_range": [2.3,15],
                "uppr_slope": 7.2,
                "uppr_slope_stddev": [11,3.7],
                "uppr_slope_range": [0.4,20],
                "lwr_slope": 2.0,
                "lwr_slope_stddev": [3.4,0.6],
                "lwr_slope_range": [0,11],
                "slope_fc": 1.2,
                "slope_fc_stddev": [2.3,0.1],
                "slope_fc_range": [0,8.4],
                "domnt_slope": 2.4,
                "domnt_slope_stddev": [4.4,0.4],
                "domnt_slope_range": [0,18]
            },
            {
                "species": "Lasionycteris noctivagans",
                "code": "Lano",
                "common_name": "Silver-haired bat",
                "fc_mean": 26.5,
                "fc_stddev": [28,25],
                "fc_range": [23,31],
                "fhi_mean": 45.9,
                "fhi_stddev": [53,39],
                "fhi_range": [27,62],
                "flo_mean": 25,
                "flo_stddev": [26,24],
                "flo_range": [20,30],
                "fmaxE_mean": 30.1,
                "fmaxE_stddev": [33,27],
                "fmaxE_range": [23,47],
                "dur_mean": 7.1,
                "dur_stddev": [10,4.2],
                "dur_range": [2,17],
                "uppr_slope": 7.1,
                "uppr_slope_stddev": [11,3.2],
                "uppr_slope_range": [0,19],
                "lwr_slope": 1.9,
                "lwr_slope_stddev": [3.7,0.1],
                "lwr_slope_range": [0,11],
                "slope_fc": 1.6,
                "slope_fc_stddev": [3,0.1],
                "slope_fc_range": [0,10],
                "domnt_slope": 2.3,
                "domnt_slope_stddev": [4.9,0],
                "domnt_slope_range": [0,18]
            },
            {
                "species": "Myotis thysanodes",
                "code": "Myth",
                "common_name": "Fringed myotis",
                "fc_mean": 25.6,
                "fc_stddev": [28,23],
                "fc_range": [20,32],
                "fhi_mean": 66.1,
                "fhi_stddev": [84,48],
                "fhi_range": [35,124],
                "flo_mean": 20.1,
                "flo_stddev": [22,18],
                "flo_range": [13,28],
                "fmaxE_mean": 29.5,
                "fmaxE_stddev": [35,24],
                "fmaxE_range": [21,71],
                "dur_mean": 3.9,
                "dur_stddev": [5.0,2.9],
                "dur_range": [1.6,6.4],
                "uppr_slope": 17.1,
                "uppr_slope_stddev": [25,10],
                "uppr_slope_range": [4,48],
                "lwr_slope": 8.6,
                "lwr_slope_stddev": [14,3.6],
                "lwr_slope_range": [1.2,37],
                "slope_fc": 6.2,
                "slope_fc_stddev": [11,1.6],
                "slope_fc_range": [0.1,32],
                "domnt_slope": 11.6,
                "domnt_slope_stddev": [19,4.2],
                "domnt_slope_range": [1.2,50]
            },
            {
                "species": "Tadarida brasiliensis",
                "code": "Tabr",
                "common_name": "Free-tailed bat",
                "fc_mean": 24.7,
                "fc_stddev": [28,21],
                "fc_range": [17,35],
                "fhi_mean": 31.4,
                "fhi_stddev": [41,22],
                "fhi_range": [18,74],
                "flo_mean": 23.1,
                "flo_stddev": [26,20],
                "flo_range": [12,35],
                "fmaxE_mean": 26.4,
                "fmaxE_stddev": [31,22],
                "fmaxE_range": [18,52],
                "dur_mean": 12.8,
                "dur_stddev": [16,9.2],
                "dur_range": [1.6,25],
                "uppr_slope": 1.6,
                "uppr_slope_stddev": [3.8,0],
                "uppr_slope_range": [0,17],
                "lwr_slope": 0.6,
                "lwr_slope_stddev": [1.5,0],
                "lwr_slope_range": [0,10],
                "slope_fc": 0.6,
                "slope_fc_stddev": [1.5,0],
                "slope_fc_range": [0,11],
                "domnt_slope": 0.6,
                "domnt_slope_stddev": [1.8,0],
                "domnt_slope_range": [0,15]
            },
            {
                "species": "Corynorhinus townsendii",
                "code": "Coto",
                "common_name": "Townsend's big-eared bat",
                "fc_mean": 28.0,
                "fc_stddev": [32,24],
                "fc_range": [19,34],
                "fhi_mean": 42.7,
                "fhi_stddev": [44,39],
                "fhi_range": [34,51],
                "flo_mean": 24.3,
                "flo_stddev": [27,21],
                "flo_range": [17,45],
                "fmaxE_mean": 32.8,
                "fmaxE_stddev": [36,29],
                "fmaxE_range": [22,45],
                "dur_mean": 3.5,
                "dur_stddev": [5.1,1.9],
                "dur_range": [1.6,14],
                "uppr_slope": 6.2,
                "uppr_slope_stddev": [8.1,4.2],
                "uppr_slope_range": [0,15],
                "lwr_slope": 5.3,
                "lwr_slope_stddev": [7.1,3.4],
                "lwr_slope_range": [0,16],
                "slope_fc": 4.9,
                "slope_fc_stddev": [7.2,2.5],
                "slope_fc_range": [0.1,23],
                "domnt_slope": 5.5,
                "domnt_slope_stddev": [7.34,3.7],
                "domnt_slope_range": [0,17]
            },
            {
                "species": "Lasiurus cinereus",
                "code": "Laci",
                "common_name": "Hoary bat",
                "fc_mean": 21.7,
                "fc_stddev": [25,18],
                "fc_range": [16,34],
                "fhi_mean": 28.9,
                "fhi_stddev": [38,20],
                "fhi_range": [16,64],
                "flo_mean": 21.1,
                "flo_stddev": [24,18],
                "flo_range": [15,32],
                "fmaxE_mean": 22.8,
                "fmaxE_stddev": [26,19],
                "fmaxE_range": [16,39],
                "dur_mean": 9.9,
                "dur_stddev": [14,6],
                "dur_range": [2,30],
                "uppr_slope": 2.2,
                "uppr_slope_stddev": [4.9,0],
                "uppr_slope_range": [0,22],
                "lwr_slope": 0.5,
                "lwr_slope_stddev": [1.3,0],
                "lwr_slope_range": [0,9.5],
                "slope_fc": 0.6,
                "slope_fc_stddev": [1.4,0],
                "slope_fc_range": [0,9.5],
                "domnt_slope": 0.8,
                "domnt_slope_stddev": [1.9,0],
                "domnt_slope_range": [0,16]
            },
            {
                "species": "Nyctinomops femorosaccus",
                "code": "Nyfe",
                "common_name": "Pocketed free-tailed bat",
                "fc_mean": 19.9,
                "fc_stddev": [22,18],
                "fc_range": [14,28],
                "fhi_mean": 29.7,
                "fhi_stddev": [36,23],
                "fhi_range": [16,47],
                "flo_mean": 18.4,
                "flo_stddev": [20,16],
                "flo_range": [13,24],
                "fmaxE_mean": 22.3,
                "fmaxE_stddev": [25,19],
                "fmaxE_range": [15,38],
                "dur_mean": 9.5,
                "dur_stddev": [11,7.9],
                "dur_range": [3.9,15],
                "uppr_slope": 2.4,
                "uppr_slope_stddev": [3.9,0.9],
                "uppr_slope_range": [0,11],
                "lwr_slope": 0.6,
                "lwr_slope_stddev": [1,0.3],
                "lwr_slope_range": [0,3.4],
                "slope_fc": 0.6,
                "slope_fc_stddev": [1,0.2],
                "slope_fc_range": [0,3.7],
                "domnt_slope": 1.1,
                "domnt_slope_stddev": [1.8,0.4],
                "domnt_slope_range": [0,5.3]
            },
            {
                "species": "Nyctinomops macrotis",
                "code": "Nyma",
                "common_name": "Big freetailed bat",
                "fc_mean": 12.7,
                "fc_stddev": [14,11],
                "fc_range": [11,15],
                "fhi_mean": 14.8,
                "fhi_stddev": [17,12],
                "fhi_range": [12,48],
                "flo_mean": 12.1,
                "flo_stddev": [13,11],
                "flo_range": [10,15],
                "fmaxE_mean": 13.4,
                "fmaxE_stddev": [14,12],
                "fmaxE_range": [11,16],
                "dur_mean": 17,
                "dur_stddev": [22,12],
                "dur_range": [12,30],
                "uppr_slope": 0.2,
                "uppr_slope_stddev": [0.4,0.1],
                "uppr_slope_range": [0,0.7],
                "lwr_slope": 0.2,
                "lwr_slope_stddev": [0.4,0],
                "lwr_slope_range": [0,1.3],
                "slope_fc": 0.8,
                "slope_fc_stddev": [1.3,0.2],
                "slope_fc_range": [0,3.2],
                "domnt_slope": 0.1,
                "domnt_slope_stddev": [0.2,0],
                "domnt_slope_range": [0,0.4],
                "comment": "error in SonoBat fhi_range"
            },
            {
                "species": "Eumops perotis",
                "code": "Eupe",
                "common_name": "Mastiff bat",
                "fc_mean": 10.7,
                "fc_stddev": [13,8.7],
                "fc_range": [7.1,16],
                "fhi_mean": 16,
                "fhi_stddev": [20,12],
                "fhi_range": [7.5,22],
                "flo_mean": 9.6,
                "flo_stddev": [11,8],
                "flo_range": [6.7,16],
                "fmaxE_mean": 12.3,
                "fmaxE_stddev": [15,10],
                "fmaxE_range": [7.4,20],
                "dur_mean": 15.1,
                "dur_stddev": [21,9.2],
                "dur_range": [2.9,33],
                "uppr_slope": 0.6,
                "uppr_slope_stddev": [1,0.2],
                "uppr_slope_range": [0,2.3],
                "lwr_slope": 0.4,
                "lwr_slope_stddev": [0.8,0],
                "lwr_slope_range": [0,1.7],
                "slope_fc": 0.4,
                "slope_fc_stddev": [0.8,0.1],
                "slope_fc_range": [0,2.7],
                "domnt_slope": 0.5,
                "domnt_slope_stddev": [0.8,0.1],
                "domnt_slope_range": [0,1.6]
            },
            {
                "species": "Idionycteris phylottis",
                "code": "Idph",
                "common_name": "Lappet-eared bat",
                "fc_mean": 12.9,
                "fc_stddev": [15,11],
                "fc_range": [1.9,15],
                "fhi_mean": 26.1,
                "fhi_stddev": [14,32],
                "fhi_range": [18,36],
                "flo_mean": 11.5,
                "flo_stddev": [13,10],
                "flo_range": [7.3,16],
                "fmaxE_mean": 16.5,
                "fmaxE_stddev": [20,13],
                "fmaxE_range": [11,24],
                "dur_mean": 4.9,
                "dur_stddev": [6.2,3.6],
                "dur_range": [1.9,10],
                "uppr_slope": 5.2,
                "uppr_slope_stddev": [6.9,3.5],
                "uppr_slope_range": [1,11],
                "lwr_slope": 1.5,
                "lwr_slope_stddev": [2.1,0.8],
                "lwr_slope_range": [0,4.1],
                "slope_fc": 1.5,
                "slope_fc_stddev": [2.3,0.7],
                "slope_fc_range": [0,4.8],
                "domnt_slope": 3,
                "domnt_slope_stddev": [3.8,2.1],
                "domnt_slope_range": [0.7,6.3]
            },
            {
                "species": "Euderma maculatum",
                "code": "Euma",
                "common_name": "Spotted bat",
                "fc_mean": 9.3,
                "fc_stddev": [10,8.2],
                "fc_range": [7.2,12],
                "fhi_mean": 14,
                "fhi_stddev": [16,12],
                "fhi_range": [11,21],
                "flo_mean": 8.7,
                "flo_stddev": [9.7,7.6],
                "flo_range": [6.5,12],
                "fmaxE_mean": 11.3,
                "fmaxE_stddev": [13,9.8],
                "fmaxE_range": [8.4,16],
                "dur_mean": 3.8,
                "dur_stddev": [5.1,2.5],
                "dur_range": [1.7,7.1],
                "uppr_slope": 1.8,
                "uppr_slope_stddev": [2.6,1.1],
                "uppr_slope_range": [0.4,6.0],
                "lwr_slope": 1.8,
                "lwr_slope_stddev": [2.6,1.1],
                "lwr_slope_range": [0.4,5.1],
                "slope_fc": 0.9,
                "slope_fc_stddev": [1.9,0],
                "slope_fc_range": [0,8.6],
                "domnt_slope": 1.5,
                "domnt_slope_stddev": [2.1,0.9],
                "domnt_slope_range": [0.4,5.1]
            }
        ]
    }
}; 